# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-01 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(related_name='players', to='fish_app2.Game'),
        ),
    ]
