# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-03 19:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app2', '0002_auto_20190101_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_finished',
            new_name='game_over',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='books',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player_index',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
    ]
