# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-04 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app2', '0004_auto_20190103_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='booked_cards',
        ),
        migrations.AddField(
            model_name='player',
            name='books',
            field=models.TextField(default="'[]'"),
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.TextField(default="'[]'"),
        ),
    ]
