# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(related_name='liked_quotess', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='login_app.User'),
        ),
    ]
