# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_auto_20181217_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteManager',
        ),
    ]
