# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-13 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2018, 12, 12)),
            preserve_default=False,
        ),
    ]
